const SERVICE_LABELS = new Map(
  [
    ["Temizlik", "تنظيف"],
    ["Ev Temizliği", "تنظيف المنازل"],
    ["Ofis Temizliği", "تنظيف المكاتب"],
    ["Halı Yıkama", "غسيل السجاد"],
    ["Cam Temizliği", "تنظيف الزجاج"],
    ["İnşaat Sonrası Temizlik", "تنظيف بعد البناء"],
    ["Koltuk Yıkama", "تنظيف الكنب"],
    ["Perde Yıkama", "غسيل الستائر"],
    ["Fabrika Temizliği", "تنظيف المصانع"],
    ["Boya & Badana", "دهان وطلاء"],
    ["Boyama & Badana", "دهان وطلاء"],
    ["İç Cephe Boya", "دهان داخلي"],
    ["Dış Cephe Boya", "دهان خارجي"],
    ["Alçı Sıva İşleri", "أعمال الجبس واللياسة"],
    ["Duvar Kağıdı Uygulaması", "تركيب ورق الجدران"],
    ["Dekoratif Boya", "دهان ديكوري"],
    ["Rulo ile Boya", "دهان بالرول"],
    ["Fırça ile Boya", "دهان بالفرشاة"],
    ["Tavan Boyama", "دهان الأسقف"],
    ["Elektrik", "كهرباء"],
    ["Elektrikçi", "كهربائي"],
    ["Tesisat Çekimi", "تمديدات كهربائية"],
    ["Arıza Tespiti", "كشف الأعطال"],
    ["Sigorta Değişimi", "تبديل القواطع"],
    ["Aydınlatma Montajı", "تركيب الإنارة"],
    ["Kombi Bağlantısı", "توصيل التدفئة"],
    ["Elektrik Panosu", "لوحة كهرباء"],
    ["Topraklama", "تأريض"],
    ["Kaçak Akım Rölesi", "قاطع تسريب التيار"],
    ["Bahçe Bakım", "عناية بالحدائق"],
    ["Bahçe & Peyzaj", "حدائق وتنسيق"],
    ["Çim Biçme", "قص العشب"],
    ["Bitki Budama", "تقليم النباتات"],
    ["Ağaç Bakımı", "العناية بالأشجار"],
    ["Peyzaj Düzenleme", "تنسيق الحدائق"],
    ["Sulama Sistemi", "نظام ري"],
    ["Çiçek Dikimi", "زراعة الزهور"],
    ["Yabani Ot Temizliği", "تنظيف الأعشاب"],
    ["Gübreleme", "تسميد"],
    ["Marangoz", "نجار"],
    ["Mobilya Tamiri", "تصليح الأثاث"],
    ["Kapı Tamiri", "تصليح الأبواب"],
    ["Dolap Montajı", "تركيب الخزائن"],
    ["Parke Döşeme", "تركيب باركيه"],
    ["Ahşap Mobilya Yapımı", "تصنيع أثاث خشبي"],
    ["Mutfak Dolabı", "خزائن مطبخ"],
    ["Gömme Dolap", "خزانة جدارية"],
    ["Ahşap Kapı", "باب خشبي"],
    ["Güzellik & Bakım", "تجميل وعناية"],
    ["Kuaför & Güzellik", "حلاقة وتجميل"],
    ["Saç Kesimi", "قص شعر"],
    ["Makyaj", "مكياج"],
    ["Cilt Bakımı", "عناية بالبشرة"],
    ["Manikür-Pedikür", "مانيكير وبيديكير"],
    ["Epilasyon", "إزالة الشعر"],
    ["Kaş Tasarımı", "تصميم الحواجب"],
    ["Masaj", "مساج"],
    ["Saç Boyama", "صبغ الشعر"],
    ["Fotoğraf & Video", "تصوير وفيديو"],
    ["Düğün Fotoğrafçılığı", "تصوير أعراس"],
    ["Portre Çekimi", "تصوير بورتريه"],
    ["Ürün Çekimi", "تصوير منتجات"],
    ["Kamera ile Çekim", "تصوير بالكاميرا"],
    ["Video Kurgu", "مونتاج فيديو"],
    ["Drone ile Çekim", "تصوير درون"],
    ["Konser Fotoğrafçılığı", "تصوير حفلات"],
    ["Event Fotoğrafçılığı", "تصوير فعاليات"],
    ["Sağlık & Terapi", "صحة وعلاج"],
    ["Terapi & Koçluk", "علاج واستشارات"],
    ["Fizyoterapi", "علاج فيزيائي"],
    ["Psikolojik Danışmanlık", "استشارة نفسية"],
    ["Diyetisyen", "أخصائي تغذية"],
    ["Masaj Terapi", "علاج بالمساج"],
    ["Nefes Terapisi", "علاج تنفس"],
    ["Yaşam Koçluğu", "تدريب حياة"],
    ["Aile Danışmanlığı", "استشارات أسرية"],
    ["Ergoterapi", "علاج وظيفي"],
    ["Oto Bakım & Tamir", "صيانة وتصليح سيارات"],
    ["Periyodik Bakım", "صيانة دورية"],
    ["Motor Tamiri", "تصليح محرك"],
    ["Kaporta Boya", "سمكرة ودهان"],
    ["Lastik Değişimi", "تغيير إطارات"],
    ["Fren Bakımı", "صيانة فرامل"],
    ["Elektrik-Arıza", "أعطال كهرباء السيارة"],
    ["Klima Bakımı", "صيانة مكيف"],
    ["Egzoz Tamiri", "تصليح عادم"],
    ["Organizasyon", "تنظيم فعاليات"],
    ["Düğün Organizasyonu", "تنظيم أعراس"],
    ["Toplantı Organizasyonu", "تنظيم اجتماعات"],
    ["Konser Organizasyonu", "تنظيم حفلات"],
    ["Etkinlik Planlama", "تخطيط فعاليات"],
    ["Kokteyl Organizasyonu", "تنظيم استقبال"],
    ["Parti Organizasyonu", "تنظيم حفلات خاصة"],
    ["Açılış Organizasyonu", "تنظيم افتتاح"],
    ["Mekan Dekorasyonu", "ديكور مكان"],
    ["Tadilat & Renovasyon", "ترميم وتجديد"],
    ["Tadilat & Dekorasyon", "ترميم وديكور"],
    ["Banyo Tadilatı", "ترميم حمام"],
    ["Mutfak Tadilatı", "ترميم مطبخ"],
    ["Alçıpan İşleri", "أعمال جبس بورد"],
    ["Seramik Döşeme", "تركيب سيراميك"],
    ["Parke Yenileme", "تجديد باركيه"],
    ["Duvar Örme", "بناء جدران"],
    ["Çatı Tamiri", "تصليح سقف"],
    ["İzolasyon", "عزل"],
    ["Tesisat", "سباكة"],
    ["Tesisatçı", "سباك"],
    ["Su Tesisatı", "تمديدات مياه"],
    ["Su Kaçağı Tespiti", "كشف تسرب مياه"],
    ["Musluk Tamiri", "تصليح حنفية"],
    ["Klozet Montajı", "تركيب مرحاض"],
    ["Petek Temizliği", "تنظيف ردياتير"],
    ["Batarya Değişimi", "تبديل خلاط"],
    ["Kombi Bakımı", "صيانة تدفئة"],
    ["Doğalgaz Tesisatı", "تمديدات غاز"],
    ["Şofben Tamiri", "تصليح سخان"],
    ["Nakliyat", "نقل"],
    ["Evden Eve Nakliyat", "نقل من منزل لمنزل"],
    ["Ofis Taşıma", "نقل مكاتب"],
    ["Parça Eşya Taşıma", "نقل قطع أثاث"],
    ["Asansörlü Taşıma", "نقل برافعة"],
    ["Paketleme Hizmeti", "خدمة تغليف"],
    ["Şehirlerarası Nakliyat", "نقل بين المدن"],
    ["Sigortalı Taşıma", "نقل مؤمن"],
    ["Mobilya Montajı", "تركيب أثاث"],
    ["Klima & Kombi", "مكيف وتدفئة"],
    ["Klima Servisi", "صيانة مكيفات"],
    ["Klima Montajı", "تركيب مكيف"],
    ["Kombi Montajı", "تركيب تدفئة"],
    ["Gaz Dolumu", "تعبئة غاز"],
    ["Kanal Açma", "فتح مجاري"],
    ["Isıtma Sistemi", "نظام تدفئة"],
    ["Çilingir", "قفال"],
    ["Kapı Açma", "فتح أبواب"],
    ["Kilit Değişimi", "تبديل قفل"],
    ["Çelik Kapı Kilidi", "قفل باب حديد"],
    ["Kasa Açma", "فتح خزنة"],
    ["Oto Kapı Açma", "فتح سيارة"],
    ["Şifreli Kilit", "قفل رقمي"],
    ["Kopuk Kilit", "تصليح قفل مكسور"],
    ["Elektronik Kilit", "قفل إلكتروني"],
    ["Eğitim & Özel Ders", "تعليم ودروس خصوصية"],
    ["Özel Ders", "دروس خصوصية"],
    ["Matematik Dersi", "درس رياضيات"],
    ["Türkçe Dersi", "درس تركي"],
    ["Fen Bilgisi Dersi", "درس علوم"],
    ["Yabancı Dil Dersi", "درس لغة أجنبية"],
    ["Müzik Dersi", "درس موسيقى"],
    ["Resim Dersi", "درس رسم"],
    ["Sınav Hazırlık", "تحضير امتحانات"],
    ["LGS-YKS Hazırlık", "تحضير LGS-YKS"],
    ["Yazılım & Teknoloji", "برمجة وتقنية"],
    ["Bilgisayar & Yazılım", "كمبيوتر وبرمجيات"],
    ["Web Tasarım", "تصميم مواقع"],
    ["Web Tasarımı", "تصميم مواقع"],
    ["Mobil Uygulama", "تطبيقات جوال"],
    ["Yazılım Geliştirme", "تطوير برمجيات"],
    ["Veri Tabanı Yönetimi", "إدارة قواعد بيانات"],
    ["Sistem Kurulumu", "تركيب أنظمة"],
    ["Network Kurulumu", "تركيب شبكات"],
    ["Teknik Destek", "دعم تقني"],
    ["Virüs Temizleme", "إزالة فيروسات"],
    ["Hukuk & Danışmanlık", "قانون واستشارات"],
    ["Avukatlık", "محاماة"],
    ["Hukuki Danışmanlık", "استشارة قانونية"],
    ["Sözleşme Hazırlama", "إعداد عقود"],
    ["İcra Takibi", "متابعة تنفيذ"],
    ["Boşanma Davası", "دعوى طلاق"],
    ["İş Hukuku", "قانون العمل"],
    ["Gayrimenkul Hukuku", "قانون عقارات"],
    ["Ticaret Hukuku", "قانون تجاري"],
    ["Veteriner", "طبيب بيطري"],
    ["Evcil Hayvan", "حيوانات أليفة"],
    ["Evcil Hayvan Muayenesi", "فحص حيوان أليف"],
    ["Aşılama", "تلقيح"],
    ["Ameliyat", "عملية"],
    ["Diş Tedavisi", "علاج أسنان"],
    ["Acil Müdahale", "تدخل إسعافي"],
    ["Hayvan Bakımı", "عناية بالحيوانات"],
    ["Parazit Tedavisi", "علاج طفيليات"],
    ["Röntgen", "تصوير أشعة"],
    ["Muhasebe", "محاسبة"],
    ["Pazarlama", "تسويق"],
    ["Çeviri", "ترجمة"],
    ["Yemek & Catering", "طعام وضيافة"],
  ].map(([key, value]) => [key.normalize("NFC"), value])
);

export function toArabicServiceLabel(value) {
  const label = String(value || "").trim();
  if (!label) return "";
  return SERVICE_LABELS.get(label.normalize("NFC")) || label;
}
